tryna fix bug
Error: 4 [ERROR] edu.hw10.task_2.ProxyInDiskTest.inDiskTest1 -- Time elapsed: 0.007 s <<< ERROR!
java.lang.RuntimeException: java.nio.file.NoSuchFileException: src/test/resources/hw10/FibImpl.txt
	at edu.hw10.task_2.CacheProxy.createFile(CacheProxy.java:170)
	at edu.hw10.task_2.CacheProxy.cacheToDisk(CacheProxy.java:89)
	at edu.hw10.task_2.CacheProxy.invoke(CacheProxy.java:55)
	at jdk.proxy2/jdk.proxy2.$Proxy72.fib(Unknown Source)
	at edu.hw10.task_2.ProxyInDiskTest.inDiskTest1(ProxyInDiskTest.java:27)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.nio.file.NoSuchFileException: src/test/resources/hw10/FibImpl.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.createFile(Files.java:657)
	at edu.hw10.task_2.CacheProxy.createFile(CacheProxy.java:168)